version: '3.8'

services:
  opd-db:
    image: postgres:13
    environment:
      POSTGRES_DB: opd_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5439:5432"
    volumes:
      - opd_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d opd_db"]
      interval: 30s
      timeout: 10s
      retries: 5

  opd-service:
    build: .
    ports:
      - "8009:8009"
    environment:
      DATABASE_URL: postgresql://user:password@opd-db:5432/opd_db
      DEBUG: "true"
    depends_on:
      opd-db:
        condition: service_healthy
    volumes:
      - .:/app

volumes:
  opd_data:
