version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: hms
      POSTGRES_USER: hms
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-strong-db-password-2024}"
    volumes:
    - pgdata:/var/lib/postgresql/data
    ports:
    - 5432:5432
  redis:
    image: redis:7-alpine
    ports:
    - 6379:6379
  rabbitmq:
    image: rabbitmq:3-management
    ports:
    - 5672:5672
    - 15672:15672
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:-strong-django-secret-key-2024}
      DJANGO_DEBUG: 'false'
      ALLOWED_HOSTS: '*'
      POSTGRES_DB: hms
      POSTGRES_USER: hms
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-strong-db-password-2024}"
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      SERVICE_JWT: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
      AUDIT_SERVICE_URL: http://audit_service:9015/api/audit/events
      SERVICE_SHARED_KEY: ${SERVICE_SHARED_KEY:-strong-shared-key-2024}
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel_collector:4317
      KAFKA_BROKER: kafka:9092
    depends_on:
    - db
    - redis
    ports:
    - 8000:8000
  celery_worker:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command:
    - celery
    - -A
    - hms
    - worker
    - -l
    - INFO
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:-strong-django-secret-key-2024}
      DJANGO_DEBUG: 'false'
      ALLOWED_HOSTS: '*'
      POSTGRES_DB: hms
      POSTGRES_USER: hms
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-strong-db-password-2024}"
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel_collector:4317
    depends_on:
    - backend
    - redis
  celery_beat:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command:
    - celery
    - -A
    - hms
    - beat
    - -l
    - INFO
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:-strong-django-secret-key-2024}
      DJANGO_DEBUG: 'false'
      ALLOWED_HOSTS: '*'
      POSTGRES_DB: hms
      POSTGRES_USER: hms
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-strong-db-password-2024}"
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel_collector:4317
    depends_on:
    - backend
    - redis
  patients_service:
    build:
      context: services/patients
    environment:
      PATIENTS_DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER:-hms_user}:${POSTGRES_PASSWORD:-strong-db-password-2024}@db:5432/${POSTGRES_DB:-hms_db}?sslmode=require
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel_collector:4317
    depends_on:
    - db
  appointments_service:
    build:
      context: services/appointments
    environment:
      APPOINTMENTS_DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER:-hms_user}:${POSTGRES_PASSWORD:-strong-db-password-2024}@db:5432/${POSTGRES_DB:-hms_db}?sslmode=require
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel_collector:4317
    depends_on:
    - db
    - rabbitmq
  billing_service:
    build:
      context: services/billing
    environment:
      BILLING_DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER:-hms_user}:${POSTGRES_PASSWORD:-strong-db-password-2024}@db:5432/${POSTGRES_DB:-hms_db}?sslmode=require
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel_collector:4317
    depends_on:
    - db
  pharmacy_service:
    build:
      context: services/pharmacy
    environment:
      PHARMACY_DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER:-hms_user}:${POSTGRES_PASSWORD:-strong-db-password-2024}@db:5432/${POSTGRES_DB:-hms_db}?sslmode=require
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel_collector:4317
    depends_on:
    - db
  lab_service:
    build:
      context: services/lab
    environment:
      LAB_DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER:-hms_user}:${POSTGRES_PASSWORD:-strong-db-password-2024}@db:5432/${POSTGRES_DB:-hms_db}?sslmode=require
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel_collector:4317
    depends_on:
    - db
  hr_service:
    build:
      context: services/hr
    environment:
      HR_DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER:-hms_user}:${POSTGRES_PASSWORD:-strong-db-password-2024}@db:5432/${POSTGRES_DB:-hms_db}?sslmode=require
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel_collector:4317
    depends_on:
    - db
  facilities_service:
    build:
      context: services/facilities
    environment:
      FACILITIES_DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER:-hms_user}:${POSTGRES_PASSWORD:-strong-db-password-2024}@db:5432/${POSTGRES_DB:-hms_db}?sslmode=require
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel_collector:4317
    depends_on:
    - db
  price_estimator_service:
    build:
      context: services/price_estimator
    environment:
      JWT_SECRET: ${JWT_SECRET:-strong-jwt-secret-2024}
      JWT_ALG: HS256
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER:-hms_user}:${POSTGRES_PASSWORD:-strong-db-password-2024}@db:5432/${POSTGRES_DB:-hms_db}?sslmode=require
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel_collector:4317
    depends_on:
    - backend
    ports:
    - 9007:9007
  bed_management_service:
    build:
      context: services/bed_management
    environment:
      BED_DATABASE_URL: postgresql+psycopg2://hms:hms@db:5432/hms
      JWT_SECRET: ${JWT_SECRET:-strong-jwt-secret-2024}
      JWT_ALG: HS256
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel_collector:4317
    depends_on:
    - backend
    ports:
    - 9008:9008
  triage_service:
    build:
      context: services/triage
    environment:
      JWT_SECRET: ${JWT_SECRET:-strong-jwt-secret-2024}
      JWT_ALG: HS256
      TRIAGE_DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER:-hms_user}:${POSTGRES_PASSWORD:-strong-db-password-2024}@db:5432/${POSTGRES_DB:-hms_db}?sslmode=require
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel_collector:4317
      OPA_URL: http://opa:8181
    depends_on:
    - backend
    ports:
    - 9009:9009
  analytics_service:
    build:
      context: services/analytics_service
    environment:
      JWT_SECRET: ${JWT_SECRET:-strong-jwt-secret-2024}
      JWT_ALG: HS256
      ANALYTICS_DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER:-hms_user}:${POSTGRES_PASSWORD:-strong-db-password-2024}@db:5432/${POSTGRES_DB:-hms_db}?sslmode=require
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel_collector:4317
      OPA_URL: http://opa:8181
      OTEL_RESOURCE_ATTRIBUTES: service.name=analytics_service,service.version=1.2.0
    depends_on:
    - backend
    ports:
    - 9010:9010
  notifications_service:
    build:
      context: services/notifications
    environment:
      NOTIFICATIONS_DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER:-hms_user}:${POSTGRES_PASSWORD:-strong-db-password-2024}@db:5432/${POSTGRES_DB:-hms_db}?sslmode=require
      JWT_SECRET: ${JWT_SECRET:-strong-jwt-secret-2024}
      JWT_ALG: HS256
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel_collector:4317
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_SENDER: ${SMTP_SENDER}
      SMS_PROVIDER_URL: ${SMS_PROVIDER_URL}
      SMS_PROVIDER_TOKEN: ${SMS_PROVIDER_TOKEN}
      FCM_SERVER_KEY: ${FCM_SERVER_KEY}
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: ${VAULT_TOKEN:-strong-vault-token-2024}
      VAULT_SECRET_PATH: secret/data/notifications
    depends_on:
    - backend
    ports:
    - 9011:9011
  graphql_gateway:
    build:
      context: services/graphql_gateway
    environment:
      PORT: 9020
      ANALYTICS_URL: http://analytics_service:9010
      TRIAGE_URL: http://triage_service:9009
      RADIOLOGY_URL: http://radiology_service:9012
      BED_URL: http://bed_management_service:9008
      BACKEND_URL: http://backend:8000
      SERVICE_SHARED_KEY: ${SERVICE_SHARED_KEY:-strong-shared-key-2024}
    depends_on:
    - analytics_service
    - triage_service
    ports:
    - 9020:9020
  radiology_service:
    build:
      context: services/radiology
    environment:
      RADIOLOGY_DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER:-hms_user}:${POSTGRES_PASSWORD:-strong-db-password-2024}@db:5432/${POSTGRES_DB:-hms_db}?sslmode=require
      JWT_SECRET: ${JWT_SECRET:-strong-jwt-secret-2024}
      JWT_ALG: HS256
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel_collector:4317
      OTEL_RESOURCE_ATTRIBUTES: service.name=radiology_service,service.version=1.2.0
    depends_on:
    - backend
    ports:
    - 9012:9012
  feedback_service:
    build:
      context: services/feedback
    environment:
      FEEDBACK_DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER:-hms_user}:${POSTGRES_PASSWORD:-strong-db-password-2024}@db:5432/${POSTGRES_DB:-hms_db}?sslmode=require
      JWT_SECRET: ${JWT_SECRET:-strong-jwt-secret-2024}
      JWT_ALG: HS256
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel_collector:4317
    depends_on:
    - backend
    ports:
    - 9013:9013
  consent_service:
    build:
      context: services/consent
    environment:
      CONSENT_DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER:-hms_user}:${POSTGRES_PASSWORD:-strong-db-password-2024}@db:5432/${POSTGRES_DB:-hms_db}?sslmode=require
      JWT_SECRET: ${JWT_SECRET:-strong-jwt-secret-2024}
      JWT_ALG: HS256
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel_collector:4317
    depends_on:
    - backend
    ports:
    - 9014:9014
  audit_service:
    build:
      context: services/audit
    environment:
      AUDIT_DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER:-hms_user}:${POSTGRES_PASSWORD:-strong-db-password-2024}@db:5432/${POSTGRES_DB:-hms_db}?sslmode=require
      JWT_SECRET: ${JWT_SECRET:-strong-jwt-secret-2024}
      JWT_ALG: HS256
      REDIS_URL: redis://redis:6379/0
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel_collector:4317
    depends_on:
    - backend
    ports:
    - 9015:9015
  er_alerts_service:
    build:
      context: services/er_alerts
    environment:
      ER_ALERTS_DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER:-hms_user}:${POSTGRES_PASSWORD:-strong-db-password-2024}@db:5432/${POSTGRES_DB:-hms_db}?sslmode=require
      JWT_SECRET: ${JWT_SECRET:-strong-jwt-secret-2024}
      JWT_ALG: HS256
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel_collector:4317
    depends_on:
    - backend
    ports:
    - 9016:9016
  ot_scheduling_service:
    build:
      context: services/ot_scheduling
    environment:
      OT_SCHED_DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER:-hms_user}:${POSTGRES_PASSWORD:-strong-db-password-2024}@db:5432/${POSTGRES_DB:-hms_db}?sslmode=require
      JWT_SECRET: ${JWT_SECRET:-strong-jwt-secret-2024}
      JWT_ALG: HS256
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel_collector:4317
    depends_on:
    - backend
    ports:
    - 9017:9017
  prometheus:
    image: prom/prometheus:latest
    volumes:
    - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    - ./observability/prometheus/alerts.yml:/etc/prometheus/alerts.yml:ro
    - prometheus_data:/prometheus
    ports:
    - 9090:9090
    depends_on:
    - price_estimator_service
    - bed_management_service
    - triage_service
    - analytics_service
    - notifications_service
    - radiology_service
    - feedback_service
    - consent_service
    - audit_service
    - er_alerts_service
    - ot_scheduling_service
  alertmanager:
    image: prom/alertmanager:latest
    command:
    - --config.file=/etc/alertmanager/alertmanager.yml
    environment:
      SLACK_WEBHOOK_URL: http://alertmanager:9093/api/v2/alerts/slack
    volumes:
    - ./observability/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    ports:
    - 9093:9093
    depends_on:
    - prometheus
  grafana:
    image: grafana/grafana-oss:latest
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
      GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:-strong-grafana-password-2024}
    ports:
    - 3001:3000
    volumes:
    - grafana_data:/var/lib/grafana
    - ./observability/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    - ./observability/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    - ./observability/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
    - prometheus
    - alertmanager
  opa:
    image: openpolicyagent/opa:0.64.1
    command:
    - run
    - --server
    - /policies/policy.rego
    volumes:
    - ./security/opa:/policies:ro
    ports:
    - 8181:8181
  vault:
    image: hashicorp/vault:1.17
    cap_add:
    - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    ports:
    - 8200:8200
  frontend:
    build:
      context: frontend
    depends_on:
    - backend
    - patients_service
    - appointments_service
    - billing_service
    - pharmacy_service
    - lab_service
    - hr_service
    - facilities_service
    - price_estimator_service
    - bed_management_service
    - triage_service
    - analytics_service
    - notifications_service
    - radiology_service
    - feedback_service
    - consent_service
    - audit_service
    ports:
    - 3000:80
volumes:
  pgdata: null
  prometheus_data: null
  grafana_data: null
