version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=hms.settings
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=hms
      - POSTGRES_USER=hms_user
      - POSTGRES_PASSWORD=hms_password
