receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      global:
        scrape_interval: 30s
      scrape_configs:
      - job_name: otel-collector
        static_configs:
        - targets:
          - 0.0.0.0:8888
processors:
  batch: null
  resource:
    attributes:
    - key: service.name
      from_attribute: resource.service.name
      action: insert
  memory_limiter:
    check_interval: 1s
    limit_mib: 500
exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
  logging:
    loglevel: info
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true
service:
  pipelines:
    traces:
      receivers:
      - otlp
      processors:
      - batch
      - resource
      - memory_limiter
      exporters:
      - logging
      - otlp
    metrics:
      receivers:
      - otlp
      - prometheus
      processors:
      - batch
      - resource
      - memory_limiter
      exporters:
      - prometheus
      - logging
    logs:
      receivers:
      - otlp
      processors:
      - batch
      - resource
      - memory_limiter
      exporters:
      - logging