apiVersion: apps/v1
kind: Deployment
metadata:
  name: cybersecurity-enhancements
  labels:
    app: cybersecurity-enhancements
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cybersecurity-enhancements
  template:
    metadata:
      labels:
        app: cybersecurity-enhancements
    spec:
      containers:
      - name: cybersecurity-enhancements
        image: cybersecurity-enhancements:latest
        ports:
        - containerPort: 8008
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: cybersecurity-db-secret
              key: database-url
        resources:
          requests:
            memory: 256Mi
            cpu: 250m
          limits:
            memory: 512Mi
            cpu: 500m
        livenessProbe:
          httpGet:
            path: /health
            port: 8008
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8008
          initialDelaySeconds: 5
          periodSeconds: 5