global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - 'rules/*.yml'

scrape_configs:
  - job_name: 'hms-microservices'
    static_configs:
      - targets:
        - patient-service:8000
        - auth-service:8000
        - billing-service:8000
        - appointment-service:8000
        - prescription-service:8000
        - lab-service:8000
        - imaging-service:8000
        - pharmacy-service:8000
        - nurse-service:8000
        - doctor-service:8000
        - admin-service:8000
        - reporting-service:8000
        - analytics-service:8000
        - notification-service:8000
        - scheduling-service:8000
        - emr-service:8000
        - ehr-service:8000
        - telehealth-service:8000
        - payment-service:8000
        - insurance-service:8000
        - claims-service:8000
        - inventory-service:8000
        - hr-service:8000
        - finance-service:8000
        - compliance-service:8000
        - audit-service:8000
        - security-service:8000
        - integration-service:8000
        - api-gateway:8000
        - frontend-service:8000
        - database-service:8000
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['localhost:8080']
EOF
