apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hms-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
spec:
  tls:
  - hosts:
    - hms.example.com
    secretName: hms-tls
  rules:
  - host: hms.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hms-frontend
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: hms-backend
            port:
              number: 80
