groups:
  - name: microservices.rules
    rules:
      - alert: HighErrorRate
        expr: sum(rate(http_requests_total{status=~"5.."}[5m])) / sum(rate(http_requests_total[5m])) > 0.05
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High error rate across services"
          description: "More than 5% of requests are failing with 5xx in the last 5 minutes."
      - alert: ServiceDown
        expr: up == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Service down"
          description: "The target {{ $labels.job }} is down."
  - name: slo.rules
    rules:
      - alert: HighLatencyP95
        expr: histogram_quantile(0.95, sum by (le, job) (rate(http_request_duration_seconds_bucket[5m]))) > 0.5
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High p95 latency (job={{ $labels.job }})"
          description: "p95 latency > 500ms for job {{ $labels.job }} over 10m"