route:
  receiver: 'default'
  routes:
    - matchers:
        - severity = critical
      receiver: 'slack'

receivers:
  - name: 'default'
    webhook_configs:
      - url: 'http://backend:8000/api/alerts/receive'
        send_resolved: true
  - name: 'slack'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#alerts'
        send_resolved: true
        title: '{{ .CommonLabels.alertname }}'
        text: '{{ .CommonAnnotations.description }}'