apiVersion: apps/v1
kind: Deployment
metadata:
  name: opd-management-service
  labels:
    app: opd-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: opd-management
  template:
    metadata:
      labels:
        app: opd-management
    spec:
      containers:
      - name: opd-service
        image: opd-management:latest
        ports:
        - containerPort: 8009
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: opd-db-secret
              key: database-url
        - name: DEBUG
          value: 'false'
        resources:
          requests:
            memory: 256Mi
            cpu: 250m
          limits:
            memory: 512Mi
            cpu: 500m
        livenessProbe:
          httpGet:
            path: /health
            port: 8009
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8009
          initialDelaySeconds: 5
          periodSeconds: 5