apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipd-management-deployment
  labels:
    app: ipd-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ipd-management
  template:
    metadata:
      labels:
        app: ipd-management
    spec:
      containers:
      - name: ipd-management
        image: ipd-management:latest
        ports:
        - containerPort: 8003
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: ipd-db-secret
              key: database-url
        resources:
          requests:
            memory: 256Mi
            cpu: 250m
          limits:
            memory: 512Mi
            cpu: 500m
        livenessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 5
          periodSeconds: 5
