name: Secret Scanning
true:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: TruffleHog Secret Scan
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: HEAD
        head: HEAD
        extra_args: --debug --only-verified
    - name: Gitleaks Secret Scan
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITLEAKS_ENABLE_UPLOAD: true