name: CD
on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
permissions:
  contents: read
  packages: write
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: backend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/newhms-backend:latest
            ghcr.io/${{ github.repository_owner }}/newhms-backend:${{ github.sha }}
      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: frontend
          file: frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/newhms-frontend:latest
            ghcr.io/${{ github.repository_owner }}/newhms-frontend:${{ github.sha }}
      - name: Build and push services
        uses: docker/bake-action@v5
        with:
          push: true
          files: |
            ./docker-bake.hcl