apiVersion: v1
kind: Namespace
metadata:
  name: hms-production
  labels:
    name: hms-production
    env: production
    security.istio.io/tlsMode: istio
  annotations:
    scheduler.alpha.kubernetes.io/node-selector: "node-type=production"
---
apiVersion: networking.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: hms-production
spec:
  mtls:
    mode: STRICT
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: hms-production-quota
  namespace: hms-production
spec:
  hard:
    requests.cpu: "50"
    requests.memory: 100Gi
    limits.cpu: "100"
    limits.memory: 200Gi
    persistentvolumeclaims: "50"
    pods: "100"
    services: "20"
    secrets: "50"
    configmaps: "50"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: hms-production-limits
  namespace: hms-production
spec:
  limits:
  - default:
      cpu: 1000m
      memory: 2Gi
    defaultRequest:
      cpu: 100m
      memory: 256Mi
    type: Container
  - default:
      storage: 10Gi
    type: PersistentVolumeClaim
