apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "hms.fullname" . }}-cdn-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      # CDN headers for static assets
      location ~* \.(css|js|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        add_header Cache-Control "public, max-age=31536000, immutable";
        add_header X-Cache-Status $upstream_cache_status;
      }
      # API caching
      location /api/ {
        add_header Cache-Control "private, max-age=300";
        proxy_cache hms_api_cache;
        proxy_cache_key "$scheme$request_method$host$request_uri";
        proxy_cache_valid 200 5m;
        proxy_cache_valid 404 1m;
      }
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ include "hms.fullname" . }}-tls
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /static/
        pathType: Prefix
        backend:
          service:
            name: {{ include "hms.fullname" . }}-backend
            port:
              number: 8000
      - path: /api/
        pathType: Prefix
        backend:
          service:
            name: {{ include "hms.fullname" . }}-backend
            port:
              number: 8000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "hms.fullname" . }}-frontend
            port:
              number: 3000