apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-tpa-service
  labels:
    app: insurance-tpa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: insurance-tpa
  template:
    metadata:
      labels:
        app: insurance-tpa
    spec:
      containers:
      - name: insurance-tpa-service
        image: insurance-tpa-service:latest
        ports:
        - containerPort: 8004
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: insurance-db-secret
              key: database-url
        resources:
          requests:
            memory: 256Mi
            cpu: 250m
          limits:
            memory: 512Mi
            cpu: 500m
        livenessProbe:
          httpGet:
            path: /health
            port: 8004
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8004
          initialDelaySeconds: 5
          periodSeconds: 5