name: CD
on:
  push:
    branches:
    - main
    tags:
    - v*.*.*
permissions:
  contents: read
  packages: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install backend dependencies
      run: |
        cd backend
        pip install -r requirements.txt
    - name: Run backend tests
      run: |
        cd backend
        python manage.py test --coverage
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    - name: Install frontend dependencies
      run: |
        cd frontend/hms-frontend
        npm install
    - name: Run frontend tests
      run: |
        cd frontend/hms-frontend
        npm run test:coverage
    - name: Run E2E tests
      run: |
        cd frontend/hms-frontend
        npx playwright install
        npm run test:e2e
    - name: Run security scan
      run: |
        cd backend
        bandit -r .
        safety check
  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push backend
      uses: docker/build-push-action@v6
      with:
        context: .
        file: backend/Dockerfile
        push: true
        tags: 'ghcr.io/${{ github.repository_owner }}/newhms-backend:latest

          ghcr.io/${{ github.repository_owner }}/newhms-backend:${{ github.sha }}

          '
    - name: Build and push frontend
      uses: docker/build-push-action@v6
      with:
        context: frontend
        file: frontend/Dockerfile
        push: true
        tags: 'ghcr.io/${{ github.repository_owner }}/newhms-frontend:latest

          ghcr.io/${{ github.repository_owner }}/newhms-frontend:${{ github.sha }}

          '
    - name: Build and push services
      uses: docker/bake-action@v5
      with:
        push: true
        files: './docker-bake.hcl

          '
