name: "Close stale issues and PRs"
on:
  schedule:
    - cron: "30 1 * * *"
permissions:
  contents: read
  issues: write
  pull-requests: write
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 30
          days-before-close: 7
          stale-issue-message: "This issue is stale because it has been open 30 days with no activity."
          stale-pr-message: "This PR is stale because it has been open 30 days with no activity."
          close-issue-message: "Closing due to inactivity."
          close-pr-message: "Closing due to inactivity."
          exempt-issue-labels: "pinned,security"
          exempt-pr-labels: "pinned,security"